import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Js Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='/static.css' />
        <script src='/common.js' />
      </head>

      <body className={inter.className}>
        {/* <h1>Common Layout</h1> */}
        {children}</body>
    </html>
  )
}




























